name = "forto-store-worker"
main = "worker.js"
compatibility_date = "2024-01-01"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "forto-products"
database_id = "14c53c3c-08f9-4a0e-a85a-0eca74fddf50" # Run: npx wrangler d1 info forto-products

# KV Namespace Binding
[[kv_namespaces]]
binding = "PRODUCTS_KV"
id = "507d27cf491d42c5a00d96d17d9cf348"

# Admin API Key (Set via secrets in production: npx wrangler secret put ADMIN_API_KEY)
[vars]
# ADMIN_API_KEY = "forto_secret_2026" 
